### ISSUE TITLE
[Bug] Travis CI Error: `yarn build` fails

### ISSUE THREAD

**Issue by yuki-koyama** [WISSOrg/web2019#15]
`yarn build` fails to build semantic-ui:
https://travis-ci.org/WISSOrg/web2019/builds/523740839

This should be a high-priority issue as the deployment relies on Travis CI.

**Comment by arcatdmz** [comment]
This is because Travis CI is set to use the latest Node.js, which is v12 right now.

A quick workaround for this is to fix the Node.js version to v10 or so.

**Comment by arcatdmz** [comment]
This fix:
https://github.com/WISSOrg/web2019/commit/464e2367b1bae87e0cd2b60b777ef32a385a45c7
resulted in a successful build:
https://travis-ci.org/WISSOrg/web2019/builds/526001755

Closing this issue.
